namespace Barnabus.Card
{
    public enum BARNABUS_CARD
    {
        ANGER,
        SADNESS,
        DISGUST,
        JOY,
        SURPRISE,
        FEAR,
        EMBARRASSMENT,
        GUILT,
        JEALOUSY,
        SILLINESS,
        PRIDE,
        BOREDOM,
        FRUSTRATION,
        HURT,
        DISLIKE,
        SATISFACTION,
        CONFUSION,
        WORRY,
        IMPATIENCE,
        ANNOYANCE,
        DISAPPOINTMENT,
        EXCITEMENT,
        AMAZEMENT,
        NERVOUSNESS,
        LOVE,
    }
}
